# Generated by Django 5.2.16 on 2026-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(max_length=100, verbose_name='提供商')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('free', models.IntegerField(default=0, verbose_name='是否免费')),
                ('chinese', models.IntegerField(default=0, verbose_name='中文支持')),
                ('code_gen', models.IntegerField(default=0, verbose_name='代码生成')),
                ('writing', models.IntegerField(default=0, verbose_name='写作能力')),
                ('reasoning', models.IntegerField(default=0, verbose_name='推理能力')),
                ('image', models.IntegerField(default=0, verbose_name='图像能力')),
                ('multimodal', models.IntegerField(default=0, verbose_name='多模态')),
                ('overall', models.IntegerField(default=0, verbose_name='综合评分')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'db_table': 'ai_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PptSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='内容')),
                ('tools', models.JSONField(blank=True, null=True, verbose_name='工具列表')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'PPT幻灯片',
                'verbose_name_plural': 'PPT幻灯片',
                'db_table': 'ppt_slides',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场景名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='场景编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场景',
                'verbose_name_plural': '场景',
                'db_table': 'scenarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '场景技能关联',
                'verbose_name_plural': '场景技能关联',
                'db_table': 'scenario_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='技能编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='图标')),
                ('tool_list', models.JSONField(blank=True, null=True, verbose_name='推荐工具')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'db_table': 'skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='角色')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
                'db_table': 'user_favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_index', models.IntegerField(default=0, verbose_name='当前幻灯片')),
                ('completed', models.IntegerField(default=0, verbose_name='已完成')),
                ('total', models.IntegerField(default=10, verbose_name='总数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'db_table': 'user_progress',
                'managed': False,
            },
        ),
    ]
